FROM python:3.12-slim

WORKDIR /app

COPY ../../file_storage_service /app/file_storage_service

COPY ../../file_storage_service/requirements.txt /app

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app

CMD ["python", "file_storage_service/main.py"]
