FROM python:3.12-slim

WORKDIR /app

COPY ../../analysis_file_service /app/analysis_file_service

COPY ../../analysis_file_service/requirements.txt /app

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app

CMD ["python", "analysis_file_service/main.py"]
